NUMBER = 'Введите число: '
RIGHTNUMBER = 'Введите нужное число (от 4 до 20): '
VALUE = 'неверное значение'
COLOR = 'Введите, пожалуйста, цвет (yellow, red, blue, orange, green, pink, purple): '
RIGHTCOLOR = 'Введите, пожалуйста, правильный цвет: '